Console.Clear();
int[] array = new int[8];
Console.WriteLine("Введите первое число: ");
int n = Convert.ToInt32(Console.ReadLine());
array [0] = n;
Console.WriteLine("Введите второе число: ");
int n1 = Convert.ToInt32(Console.ReadLine());
array [1] = n1;
Console.WriteLine("Введите третье число: ");
int n2 = Convert.ToInt32(Console.ReadLine());
array [2] = n2;
Console.WriteLine("Введите четвертое число: ");
int n3 = Convert.ToInt32(Console.ReadLine());
array [3] = n3;
Console.WriteLine("Введите пятое число: ");
int n4 = Convert.ToInt32(Console.ReadLine());
array [4] = n4;
Console.WriteLine("Введите шестое число: ");
int n5 = Convert.ToInt32(Console.ReadLine());
array [5] = n5;
Console.WriteLine("Введите седьмое число: ");
int n6 = Convert.ToInt32(Console.ReadLine());
array [6] = n6;
Console.WriteLine("Введите восьмое число: ");
int n7 = Convert.ToInt32(Console.ReadLine());
array [7] = n7;
Console.WriteLine($"[{string.Join(", ", array)}]");